### ISSUE TITLE
pbreports.report.barcode is returning index not name

### ISSUE THREAD

**Issue by mp15** [PacificBiosciences/pbreports#250]
The barcode report appears to be returning ID/index of a barcode rather than the name of the barcode which is meaningful to downstream users. It appears the problem may originate here: 
https://github.com/PacificBiosciences/pbreports/blob/master/pbreports/report/barcode.py#L66

**Comment by natechols** [comment]
The code you pointed to should already be using the ID from the FASTA header, not the index.  Are you running pbreports directly, or looking at one of the distributed smrtlink releases?

**Comment by mp15** [comment]
I've observed this behaviour with the barcoding and barcoding+LAA pipelines from SMRT Link 4.0.0.190159 and earlier version of SMRTLink too (with directory name smrtlink-fromsrc_3.1.1.182868,182868-182868-182483-182249-182249) I have replicated the behaviour on both the command link using pbsmrtpipe and from the web GUI. Curiously the "Amplicon Consensus Summary" also yields indexes (aka 0--0) in version 3.1.1 but yields names (aka lbc1--lbc1) in version 4.0.0.

**Comment by natechols** [comment]
Okay, this is indeed a known bug in currently available smrtlink releases through 4.0.0 - however it has already been fixed for the next version (which is reflected in the code on GitHub).  I'm pretty sure we're consistently using the same convention everywhere now.

**Comment by mp15** [comment]
Thanks @natechols I had missed it, resolved by #248 but too late to make the January release. I'll see if I can drop the patch onto my precompiled SMRT commands then (alas bam2bam and laa source isn't available otherwise I'd run the whole thing from git).
